version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: mybd
    volumes:
      - db-data:/var/lib/postgresql/data2
    ports:
      - "5432:5432"
volumes:
  db-data:
